---

- name: Setup Docker repo key
  apt_key:
    keyserver: "hkp://keyserver.ubuntu.com:80"
    id: "36A1D7869245C8950F966E92D8576A8BA88D21E9"

- name: Setup Docker repo path
  apt_repository:
    repo: 'deb https://get.docker.com/ubuntu docker main'
    state: present

- name: Install docker
  apt:
    name: lxc-docker

- name: Bind docker to mallard 10.0.0.0/24 network
  lineinfile:
    dest: /etc/default/docker
    regexp: ^DOCKER_OPTS
    line: 'DOCKER_OPTS="--dns 8.8.8.8 --dns 8.8.4.4 -H {{ ansible_mallard["ipv4"]["address"] }}:2375 -H unix:///var/run/docker.sock"'
  notify: restart docker

- name: Install docker swarm agent init script
  template:
    src: swarm-agent.conf.j2
    dest: /etc/init/swarm-agent.conf

- name: Install docker swarm manager init script
  template:
    src: swarm-manager.conf.j2
    dest: /etc/init/swarm-manager.conf

- name: Do not start on boot (let monit manage that)
  service: name={{ item }} enabled=no
  with_items:
    - docker
    - swarm-agent
    - swarm-manager
