---

- name: Download consul
  get_url:
    url: "https://dl.bintray.com/mitchellh/consul/{{ consul.filename }}"
    dest: "/var/tmp/{{ consul.filename }}"
    sha256sum: "{{ consul.sha256 }}"
  register: consul_downloaded

- name: Install unzip
  apt: name=unzip

- name: Install consul
  shell: "unzip -o /var/tmp/{{ consul.filename }} chdir=/usr/local/bin"
  when: consul_downloaded|changed

- name: Create consul group
  group: name={{ consul.user }} state=present

- name: Create consul user
  user: name=consul group={{ consul.user }} state=present

- name: Setup consul directories (root user)
  file: path={{ item }} owner=root group=root state=directory
  with_items:
    - /etc/consul.d

- name: Setup consul directories (consul user)
  file: path={{ item }} owner={{ consul.user }} group={{ consul.group }} state=directory
  with_items:
    - /var/lib/consul

- name: Install init script
  template:
    src: consul.conf.j2
    dest: /etc/init/consul.conf
  notify: restart consul

- name: No not start consul service at boot (monit manage this)
  service: name=consul enabled=no

- name: Create /var/consul
  file: path=/var/consul state=directory

- name: Download Web UI
  get_url:
    url: https://dl.bintray.com/mitchellh/consul/0.5.0_web_ui.zip
    dest: /var/consul/0.5.0_web_ui.zip
    sha256sum: 0081d08be9c0b1172939e92af5a7cf9ba4f90e54fae24a353299503b24bb8be9
  register: new_webui

- name: Unzip Web UI
  command: unzip 0.5.0_web_ui.zip chdir=/var/consul
  when: new_webui|changed
