---

- hosts: all
  tasks:
    - name: Install monit
      apt: name=monit

    - name: Setup monitrc
      template:
        src: templates/monitrc.j2
        dest: /etc/monit/monitrc
      notify: restart monit

  handlers:
    - name: restart monit
      service: name=monit state=restarted
