---

- name: install haproxy
  apt: name=haproxy

- name: install haproxy.cfg
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
  notify: restart haproxy

- name: enable haproxy
  lineinfile:
    dest: /etc/default/haproxy
    regexp: ^ENABLED
    line: ENABLED=1
  notify: restart haproxy

- name: start on boot
  service: name=haproxy enabled=yes state=started

- name: make sure we have socat installed
  apt: name=socat
